version: '3'
services:
  web:
    build: site
    container_name: apache
    ports :
      - "81:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
      - ./server/mycert.crt:/var/www/html/mycert.crt
      - ./server/mycert.key:/var/www/html/mycert.key
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: mysql
    ports :
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mvcdocker2
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

      
      
