/:
  controller: main
  action: home




/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/loginVerify:
  controller: user
  action: loginVerify

/lostPassword:
  controller: user
  action: lostPassword

/lostPasswordAction:
  controller: user
  action: lostPasswordAction

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/googleConnect:
  controller: user
  action: googleConnect

/facebookConnect:
  controller: user
  action: facebookConnect

/dashboard:
  controller: admin
  action: home
  security: true

/restaurant:
  controller: restaurant
  action: restaurant

/profile-restaurant:
  controller: restaurant
  action: updateRestaurant

/profile:
  controller: admin
  action: profile
  security: true
