/:
  controller: main
  action: home

/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/dashboard:
  controller: admin
  action: home
  security: true

/sendmail:
  controller: mail
  action: sendConfirmMail

/testmail:
  controller: mail
  action: index

/createToken:
  controller: user
  action: createToken

/getToken:
  controller: user
  action: getToken

/verifyToken:
  controller: user
  action: verifyToken

