/:
  controller: main
  action: home




/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/connected:
  controller: user
  action: connected

/dashboard:
  controller: admin
  action: home
  security: true
