/:
  controller: main
  action: home

/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/loginVerify:
  controller: user
  action: loginVerify

/lostPassword:
  controller: user
  action: lostPassword

/lostPasswordAction:
  controller: user
  action: lostPasswordAction

/resetPassword:
  controller: user
  action: resetPassword

/resetPasswordAction:
  controller: user
  action: resetPasswordAction

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/googleConnect:
  controller: user
  action: googleConnect

/facebookConnect:
  controller: user
  action: facebookConnect

/dashboard:
  controller: admin
  action: home
  security: 'employee'

/sendmail:
  controller: mail
  action: sendConfirmMail

/testmail:
  controller: mail
  action: index

/createToken:
  controller: user
  action: createToken

/getToken:
  controller: user
  action: getToken

/verifyToken:
  controller: user
  action: verifyToken

/restaurants:
  controller: restaurant
  action: restaurant

/restaurant/delete:
  controller: restaurant
  action: deleteRestaurant

/restaurant/create:
  controller: restaurant
  action: createOneRestaurant

/profile-restaurant:
  controller: restaurant
  action: updateRestaurant

/restaurant:
  controller: restaurant
  action: getOneRestaurant

/profile:
  controller: admin
  action: profile
  security: 'employee'

/cartes:
  controller: carte
  action: carte

/carte/create:
  controller: carte
  action: createCarte

/updateCarte:
  controller: carte
  action: updateCarte

/carte/delete:
  controller: carte
  action: deleteCarte

/carte/meals:
  controller: meal
  action: meal

/carte/meals/sendId:
  controller: meal
  action: setIdCard

/carte/meals/addCategorie:
  controller: categorie
  action: createcategorie

/carte/meals/updateCategorie:
  controller: categorie
  action: updateCategorie

/carte/meals/addMeal:
  controller: meal
  action: createMeal

/carte/meals/updateMeal:
  controller: meal
  action: updateMeal


#Route pour la reservation
/reservation:
  controller: reservation
  action: reservation
  security: 'employee'

/addReservation:
  controller: reservation
  action: addReservation
  security: 'employee'

############################
/notFound:
  controller: user
  action: errorNotFound
  security: 'employee'

