/:
  controller: main
  action: home

/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/loginVerify:
  controller: user
  action: loginVerify

/lostPassword:
  controller: user
  action: lostPassword

/lostPasswordAction:
  controller: user
  action: lostPasswordAction

/resetPassword:
  controller: user
  action: resetPassword

/resetPasswordAction:
  controller: user
  action: resetPasswordAction

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/googleConnect:
  controller: user
  action: googleConnect

/facebookConnect:
  controller: user
  action: facebookConnect

/dashboard:
  controller: admin
  action: home
  security: true

/sendmail:
  controller: mail
  action: sendConfirmMail

/testmail:
  controller: mail
  action: index

/createToken:
  controller: user
  action: createToken

/getToken:
  controller: user
  action: getToken

/verifyToken:
  controller: user
  action: verifyToken

/restaurants:
  controller: restaurant
  action: restaurant

/restaurant/delete:
  controller: restaurant
  action: deleteRestaurant

/stock:
  controller: stock
  action: stock

/restaurant/creation:
  controller: restaurant
  action: createOneRestaurant

/restaurant/create:
  controller: restaurant
  action: updateRestaurant

/restaurant/information:
  controller: restaurant
  action: getOneRestaurant

/restaurant:
  controller: restaurant
  action: restaurantOptions

/profile:
  controller: admin
  action: profile
  security: true

/notFound:
  controller: user
  action: errorNotFound

