/:
  controller: main
  action: home

/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/loginVerify:
  controller: user
  action: loginVerify

/lostPassword:
  controller: user
  action: lostPassword

/lostPasswordAction:
  controller: user
  action: lostPasswordAction

/resetPassword:
  controller: user
  action: resetPassword

/resetPasswordAction:
  controller: user
  action: resetPasswordAction

/register:
  controller: user
  action: register

/googleConnect:
  controller: user
  action: googleConnect

/facebookConnect:
  controller: user
  action: facebookConnect

/dashboard:
  controller: admin
  action: home
  security: "employee"

/sendmail:
  controller: mail
  action: sendConfirmMail

/testmail:
  controller: mail
  action: index

/createToken:
  controller: user
  action: createToken

/getToken:
  controller: user
  action: getToken

/verifyToken:
  controller: user
  action: verifyToken

/restaurants:
  controller: restaurant
  action: restaurant

/restaurant/delete:
  controller: restaurant
  action: deleteRestaurant

/restaurant/stock:
  controller: stock
  action: stock

/restaurant/food/create:
  controller: food
  action: createFood

/restaurant/food/delete:
  controller: food
  action: deleteFood

/restaurant/food:
  controller: food
  action: getOneFood

/restaurant/food/update:
  controller: food
  action: updateFood

/restaurant/creation:
  controller: restaurant
  action: createOneRestaurant

/restaurant/update:
  controller: restaurant
  action: updateRestaurant

/restaurant/create:
  controller: restaurant
  action: createRestaurantForm

/restaurant/information:
  controller: restaurant
  action: getOneRestaurant

/restaurant:
  controller: restaurant
  action: restaurantOptions

/profile:
  controller: admin
  action: profile
  security: "employee"

/profile/update:
  controller: admin
  action: updateProfile
  security: "employee"

/restaurant/cartes:
  controller: carte
  action: carte

/restaurant/carte/create:
  controller: carte
  action: createCarte

/restaurant/updateCarte:
  controller: carte
  action: updateCarte

/restaurant/carte/delete:
  controller: carte
  action: deleteCarte

/restaurant/carte/meals:
  controller: meal
  action: meal

/restaurant/carte/meals/sendId:
  controller: meal
  action: setIdCard

/restaurant/carte/meals/addCategorie:
  controller: categorie
  action: createcategorie

/restaurant/carte/meals/updateCategorie:
  controller: categorie
  action: updateCategorie

/restaurant/carte/meals/deleteCategorie:
  controller: categorie
  action: deleteCategorie

/restaurant/carte/meals/addMeal:
  controller: meal
  action: createMeal

/restaurant/carte/meals/updateMeal:
  controller: meal
  action: updateMeal

/restaurant/carte/meals/deleteMeal:
  controller: meal
  action: deleteMeal

# Route pour la reservation
/reservation:
  controller: reservation
  action: reservation
  security: "employee"

/reservationClient:
  controller: reservation
  action: index

/addReservationClient:
  controller: reservation
  action: addReservationClient

/addReservation:
  controller: reservation
  action: addReservation
  security: "employee"

/restaurant/completeReservation:
  controller: reservation
  action: completeReservation
  security: "employee"

# Route pour les commentaires

/addComment:
  controller: comment
  action: addCommentView
  security: "user"


# Route pour la gestion des utilisateurs

/users:
  controller: admin
  action: users
  security: "admin"

/user/update:
  controller: admin
  action: updateUser
  security: "admin"

/user/create:
  controller: admin
  action: createUser
  security: "admin"

/user/save:
  controller: admin
  action: saveUser
  security: "admin"

/user/delete:
  controller: admin
  action: deleteUser
  security: "admin"

############################

# Global

/logout:
  controller: user
  action: logout
  security: "user"

/notFound:
  controller: user
  action: errorNotFound
  security: "employee"
