/:
  controller: main
  action: home

/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/loginVerify:
  controller: user
  action: loginVerify

/lostPassword:
  controller: user
  action: lostPassword

/resetPassword:
  controller: user
  action: resetPassword

/register:
  controller: user
  action: register

/register/validate:
  controller: user
  action: notifyValidation

/googleConnect:
  controller: user
  action: googleConnect

/facebookConnect:
  controller: user
  action: facebookConnect

/dashboard:
  controller: admin
  action: home
  security: "employee"

/logs:
  controller: log
  action: index
  security: "employee"

/sendmail:
  controller: mail
  action: sendConfirmMail

/testmail:
  controller: mail
  action: index

/createToken:
  controller: user
  action: createToken

/getToken:
  controller: user
  action: getToken

/verifyToken:
  controller: user
  action: verifyToken

/restaurants:
  controller: restaurant
  action: restaurant
  security: "employee"

/restaurant/delete:
  controller: restaurant
  action: deleteRestaurant
  security: "admin"

/restaurant/stock:
  controller: stock
  action: stock
  security: "employee"

/restaurant/food/create:
  controller: food
  action: createFood
  security: "employee"

/restaurant/food/delete:
  controller: food
  action: deleteFood
  security: "employee"

/restaurant/food:
  controller: food
  action: getOneFood
  security: "employee"

/restaurant/food/update:
  controller: food
  action: updateFood
  security: "employee"

/restaurant/creation:
  controller: restaurant
  action: createOneRestaurant
  security: "admin"

/restaurant/update:
  controller: restaurant
  action: updateRestaurant
  security: "admin"

/restaurant/create:
  controller: restaurant
  action: createRestaurantForm
  security: "admin"

/restaurant/information:
  controller: restaurant
  action: getOneRestaurant
  security: "employee"

/restaurant/page:
  controller: page
  action: index
  security: "admin"

/page/delete:
  controller: page
  action: delete
  security: "admin"

/page/show:
  controller: page
  action: showPage
  security: "admin"

/restaurant/pagecreate:
  controller: page
  action: createPage
  security: "admin"

/restaurant/page/edit:
  controller: page
  action: edit
  security: "admin"

/restaurant/pagesave:
  controller: page
  action: savePage
  security: "admin"

/restaurant:
  controller: restaurant
  action: restaurantOptions
  security: "employee"

/profile:
  controller: admin
  action: profile
  security: "employee"

/profile/update:
  controller: admin
  action: updateProfile
  security: "employee"

/restaurant/cartes:
  controller: carte
  action: carte
  security: "employee"

/restaurant/carte/create:
  controller: carte
  action: createCarteView
  security: "admin"

/restaurant/updateCarte:
  controller: carte
  action: updateCarte
  security: "employee"

/restaurant/createCarte:
  controller: carte
  action: createCarte
  security: "admin"

/restaurant/carte/delete:
  controller: carte
  action: deleteCarte
  security: "admin"

/restaurant/carte/meals:
  controller: meal
  action: meal
  security: "employee"

/restaurant/carte/meals/sendId:
  controller: meal
  action: setIdCard
  security: "employee"


/restaurant/carte/meals/addCategorie:
  controller: categorie
  action: createcategorie
  security: "employee"

/restaurant/carte/meals/updateCategorie:
  controller: categorie
  action: updateCategorie
  security: "employee"


/restaurant/carte/meals/deleteCategorie:
  controller: categorie
  action: deleteCategorie
  security: "employee"


/restaurant/carte/meals/addMeal:
  controller: meal
  action: createMeal
  security: "employee"


/restaurant/carte/meals/updateMeal:
  controller: meal
  action: updateMeal
  security: "employee"


/restaurant/carte/meals/deleteMeal:
  controller: meal
  action: deleteMeal
  security: "employee"


/restaurant/carte/meals/deleteFoods:
  controller: mealsFoods
  action: deleteFoods
  security: "employee"


# Route pour les thèmes

/themes:
  controller: admin
  action: themes
  security: "admin"

/themes/switchTheme:
  controller: theme
  action: switchTheme
  security: "admin"

/themes/configure/:id:
  controller: theme
  action: configureThemes
  security: "admin"

/themes/update/:id:
  controller: theme
  action: updateTheme
  security: "admin"

# Route pour la reservation
/restaurant/reservation:
  controller: reservation
  action: reservation
  security: "employee"

/restaurant/validation/:id:
  controller: reservation
  action: confirmValidation
  security: "employee"

/reservationClient:
  controller: reservation
  action: index

/addReservationClient:
  controller: reservation
  action: addReservationClient

/restaurant/addReservation:
  controller: reservation
  action: addReservation
  security: "employee"

/restaurant/completeReservation:
  controller: reservation
  action: completeReservation
  security: "employee"

/reserver-une-table:
  controller: reservation
  action: reservationTable

/reserver-une-table/add:
  controller: reservation
  action: addReservationTable

/restaurant/QrcodeEdit:
  controller: restaurant
  action: QrcodeEdit

# Route pour les commentaires

/addComment:
  controller: comment
  action: addCommentView
  security: "user"

/restaurant/addComment:
  controller: comment
  action: stockComment
  security: "user"

/restaurant/comments:
  controller: comment
  action: getComments
  security: "admin"

/restaurant/validateComment:
  controller: comment
  action: validateComment
  security: "admin"

/restaurant/deleteComment:
  controller: comment
  action: deleteComment
  security: "admin"

/showComments:
  controller: comment
  action: showComments

/replyComment:
  controller: comment
  action: replyComment
  security: "user"
# Route pour la gestion des utilisateurs

/restaurant/statistiques:
  controller: stats
  action: stats
  security: "employee"

/restaurant/editReservation:
  controller: reservation
  action: edit
  security: "employee"

/restaurant/deleteReservation:
  controller: reservation
  action: delete
  security: "employee"

# Route pour la gestion des utilisateurs

/users:
  controller: admin
  action: users
  security: "admin"

/user/update/:id:
  controller: admin
  action: updateUser
  security: "admin"

/user/create:
  controller: admin
  action: createUser
  security: "admin"

/user/save:
  controller: admin
  action: saveUser
  security: "admin"

/user/delete:
  controller: admin
  action: deleteUser
  security: "admin"

############################

# Global

/logout:
  controller: user
  action: logout
  security: "user"

/theme:
  controller: theme
  action: render

/theme/:id:
  controller: theme
  action: home

/theme/story/:id:
  controller: theme
  action: story

/theme/menu/:id:
  controller: theme
  action: menu

/theme/reservation/:id:
  controller: theme
  action: reservation

/theme/contact/:id:
  controller: theme
  action: contact

/notFound:
  controller: user
  action: errorNotFound
  security: "employee"

/sitemap:
  controller: globalController
  action: sitemap

/sitemap.xml:
  controller: globalController
  action: sitemapXML

# Setup

/setup:
  controller: globalController
  action: setup

/setupAdmin:
  controller: globalController
  action: setupAdmin

/setupAction:
  controller: globalController
  action: setupAction
