/:
  controller: main
  action: home

/nous-contacter:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/loginVerify:
  controller: user
  action: loginVerify

/lostPassword:
  controller: user
  action: lostPassword

/lostPasswordAction:
  controller: user
  action: lostPasswordAction

/resetPassword:
  controller: user
  action: resetPassword

/resetPasswordAction:
  controller: user
  action: resetPasswordAction

/register:
  controller: user
  action: register

/register/validate:
  controller: user
  action: notifyValidation

/googleConnect:
  controller: user
  action: googleConnect

/facebookConnect:
  controller: user
  action: facebookConnect

/dashboard:
  controller: admin
  action: home
  security: "employee"

/sendmail:
  controller: mail
  action: sendConfirmMail

/testmail:
  controller: mail
  action: index

/createToken:
  controller: user
  action: createToken

/getToken:
  controller: user
  action: getToken

/verifyToken:
  controller: user
  action: verifyToken

/restaurants:
  controller: restaurant
  action: restaurant

/restaurant/delete:
  controller: restaurant
  action: deleteRestaurant

/restaurant/stock:
  controller: stock
  action: stock

/restaurant/food/create:
  controller: food
  action: createFood

/restaurant/food/delete:
  controller: food
  action: deleteFood

/restaurant/food:
  controller: food
  action: getOneFood

/restaurant/food/update:
  controller: food
  action: updateFood

/restaurant/creation:
  controller: restaurant
  action: createOneRestaurant

/restaurant/update:
  controller: restaurant
  action: updateRestaurant

/restaurant/create:
  controller: restaurant
  action: createRestaurantForm

/restaurant/information:
  controller: restaurant
  action: getOneRestaurant

/restaurant/page:
  controller: page
  action: index

/page/delete:
  controller: page
  action: delete

/page/show:
  controller: page
  action: showPage

/restaurant/pagecreate:
  controller: page
  action: createPage

/restaurant/page/edit:
  controller: page
  action: edit

/restaurant/pagesave:
  controller: page
  action: savePage

/restaurant:
  controller: restaurant
  action: restaurantOptions

/profile:
  controller: admin
  action: profile
  security: "employee"

/profile/update:
  controller: admin
  action: updateProfile
  security: "employee"

/restaurant/cartes:
  controller: carte
  action: carte

/restaurant/carte/create:
  controller: carte
  action: createCarteView

/restaurant/updateCarte:
  controller: carte
  action: updateCarte

/restaurant/createCarte:
  controller: carte
  action: createCarte

/restaurant/carte/delete:
  controller: carte
  action: deleteCarte

/restaurant/carte/meals:
  controller: meal
  action: meal

/restaurant/carte/meals/sendId:
  controller: meal
  action: setIdCard

/restaurant/carte/meals/addCategorie:
  controller: categorie
  action: createcategorie

/restaurant/carte/meals/updateCategorie:
  controller: categorie
  action: updateCategorie

/restaurant/carte/meals/deleteCategorie:
  controller: categorie
  action: deleteCategorie

/restaurant/carte/meals/addMeal:
  controller: meal
  action: createMeal

/restaurant/carte/meals/updateMeal:
  controller: meal
  action: updateMeal

/restaurant/carte/meals/deleteMeal:
  controller: meal
  action: deleteMeal

/restaurant/carte/meals/deleteFoods:
  controller: mealsFoods
  action: deleteFoods

# Route pour les thèmes

/themes:
  controller: admin
  action: themes
  security: "admin"

/themes/switchTheme:
  controller: theme
  action: switchTheme
  security: "admin"

# Route pour la reservation
/restaurant/reservation:
  controller: reservation
  action: reservation
  security: "employee"

/reservationClient:
  controller: reservation
  action: index

/addReservationClient:
  controller: reservation
  action: addReservationClient

/restaurant/addReservation:
  controller: reservation
  action: addReservation
  security: "employee"

/restaurant/completeReservation:
  controller: reservation
  action: completeReservation
  security: "employee"

/reserver-une-table:
  controller: reservation
  action: reservationTable

/reserver-une-table/add:
  controller: reservation
  action: addReservationTable

# Route pour les commentaires

/addComment:
  controller: comment
  action: addCommentView
  security: "user"

/restaurant/addComment:
  controller: comment
  action: stockComment
  security: "user"

/restaurant/comments:
  controller: comment
  action: getComments
  security: "admin"

/restaurant/validateComment:
  controller: comment
  action: validateComment
  security: "admin"

/restaurant/deleteComment:
  controller: comment
  action: deleteComment
  security: "admin"

/showComments:
  controller: comment
  action: showComments

# Route pour la gestion des utilisateurs

/restaurant/statistiques:
  controller: stats
  action: stats

/restaurant/editReservation:
  controller: reservation
  action: edit
  security: "employee"

/restaurant/deleteReservation:
  controller: reservation
  action: delete
  security: "employee"

# Route pour la gestion des utilisateurs

/users:
  controller: admin
  action: users
  security: "admin"

/user/update:
  controller: admin
  action: updateUser
  security: "admin"

/user/create:
  controller: admin
  action: createUser
  security: "admin"

/user/save:
  controller: admin
  action: saveUser
  security: "admin"

/user/delete:
  controller: admin
  action: deleteUser
  security: "admin"

############################

# Global

/logout:
  controller: user
  action: logout
  security: "user"

/theme:
  controller: theme
  action: render

/theme/:id:
  controller: theme
  action: home

/theme/story/:id:
  controller: theme
  action: story

/theme/menu/:id:
  controller: theme
  action: menu

/theme/reservation/:id:
  controller: theme
  action: reservation

/theme/contact/:id:
  controller: theme
  action: contact

/notFound:
  controller: user
  action: errorNotFound
  security: "employee"

/sitemap:
  controller: globalController
  action: sitemap

/sitemap.xml:
  controller: globalController
  action: sitemapXML

# Setup

/setup:
  controller: globalController
  action: setup

/setupAdmin:
  controller: globalController
  action: setupAdmin

/setupAction:
  controller: globalController
  action: setupAction

/test:
  controller: carte
  action: asupprimer
