# This is a basic workflow to help you get started with Actions

name: CI-CD-Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  connect:
    name: Connexion au serveur de recette
    runs-on: ubuntu-latest
    steps:
    - name: Connect with SSH to server
      uses: fifsky/ssh-action@master
      with:
        command: |
          sudo -i
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa_github
          cd /var/www/PA-CMS-Restaurant
          git stash
          git pull origin develop --rebase
          git status
          git stash pop
          git status
          cd www/public/webpack
          npm run build
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        key: ${{ secrets.KEY }}

